[package]
name = "wave"
version = "0.1.0"
edition = "2021"
description = "Programming Language"
license = "MPL-2"
authors = ["LunaStev <lunastev@gurmstudios.com>"]

[dependencies]
pest = "2.1"
pest_derive = "2.1"
anyhow = "1.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = [
    "llvm14-0",
] } # use correct feature according to your llvm version
rustyline = "12.0"
cfg-if = "1.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"
test = false

[[bin]]
name = "repl"
test = false

[features]
jit = []
interpreter = []
vm = []