[package]
name = "wave"
version = "0.0.8-pre-alpha"
edition = "2021"

[target.x86_64-apple-darwin]
linker = "clang"

[target.aarch64-apple-darwin]
linker = "clang"

[dependencies]
colorex = "0.1.0"
inkwell = { version = "0.5.0", features = ["llvm14-0"] }