[package]
name = "wavec"
version = "0.1.1-pre-beta"
edition = "2021"

# [target.x86_64-apple-darwin]
# linker = "clang"
# [target.aarch64-apple-darwin]
# linker = "clang"

[dependencies]
colorex = "0.1.0"
lexer = { path = "./lexer" }
parser = { path = "./parser" }
llvm_temporary = { path = "./llvm_temporary" }

[workspace]
members = [
    "lexer",
    "parser",
    "llvm_temporary",
    "error",
    ".",
]
