name: Deploy to Wave Docs Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install mdBook
        run: cargo install mdbook

      - name: Build English version
        working-directory: ./docs
        run: mdbook build --config book.toml --lang=en

      - name: Build Korean version
        working-directory: ./docs
        run: mdbook build --config book.toml --lang=ko

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: docs/book
