name: Deploy to Wave Docs Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install mdBook
        run: cargo install mdbook

      - name: Build book
        working-directory: ./docs
        run: |
          if [[ "$GITHUB_ENV" =~ LANG ]]; then
            echo "LANG=$GITHUB_ENV" >> $GITHUB_ENV
          fi
          mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: docs/book
