name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM 14 and Polly
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-14 llvm-14-dev llvm-14-tools libpolly-14
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose