name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM 14
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-14 llvm-14-dev llvm-14-tools
      - name: Set LLVM environment variables
        run: |
          export LLVM_SYS_140_PREFIX=/usr/lib/llvm-14
          export LIBCLANG_PATH=/usr/lib/llvm-14/lib
          export LD_LIBRARY_PATH=/usr/lib/llvm-14/lib:$LD_LIBRARY_PATH
      - name: Build
        run: |
          cargo clean
          cargo build --verbose -L /usr/lib/llvm-14/lib
      - name: Run tests
        run: cargo test --verbose -L /usr/lib/llvm-14/lib