name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: llvmenv Install
      run: curl -sSL https://github.com/llvmenv/llvmenv/releases/download/v0.1.0/llvmenv-linux-x86_64.tar.gz | tar xz -C $HOME
    - name: LLVM Install
      run: $HOME/llvmenv/bin/llvmenv install 14.0.0
    - name: LLVM Echo
      run: echo "LLVM_SYS_140_PREFIX=$HOME/llvmenv" >> $GITHUB_ENV
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
